### ISSUE TITLE
No icons showing

### ISSUE THREAD

**Issue by iamnewton** [SamVerschueren/alfred-css-triggers#2]
OS X El Capitan (10.11.6)
Alfred v3.3 (801)

Just installed and not getting any of the icons like in the screenshot on the README.

**Comment by SamVerschueren** [comment]
You're right. Typo in package.json. Will fix it tomorrow. Thanks for reporting!

**Comment by iamnewton** [comment]
No problem.  Thanks for creating this!!!

**Comment by SamVerschueren** [comment]
Fixed in v0.2.1 🍻
